// <auto-generated />
using System;
using HelpDesk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpDesk.Migrations
{
    [DbContext(typeof(HelpDeskDbContext))]
    partial class HelpDeskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("HelpDesk.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = "demo",
                            AuthorName = "ivan",
                            CreatedAt = new DateTime(2026, 3, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Принтер на 3 поверсі не друкує",
                            Status = "Новий",
                            Title = "Не працює принтер"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = "demo",
                            AuthorName = "ivan",
                            CreatedAt = new DateTime(2026, 3, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Не можу підключитися до корпоративного VPN з дому",
                            Status = "В роботі",
                            Title = "Потрібен доступ до VPN"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = "demo",
                            AuthorName = "ivan",
                            CreatedAt = new DateTime(2026, 3, 15, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ліцензія Microsoft Office закінчилась на моєму ПК",
                            Status = "Вирішено",
                            Title = "Оновити ліцензію Office"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
